import React, { useState, useEffect } from 'react';
import FlexSearch from 'flexsearch';

interface GlossaryTerm {
  term: string;
  definition: string;
  id: string;
}

interface GlossaryIndex {
  terms: GlossaryTerm[];
  generated: string;
}

export default function GlossarySearch(): JSX.Element {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<GlossaryTerm[]>([]);
  const [index, setIndex] = useState<FlexSearch.Index | null>(null);
  const [glossaryData, setGlossaryData] = useState<GlossaryTerm[]>([]);

  // Load glossary index on component mount
  useEffect(() => {
    async function loadGlossary() {
      try {
        // Fetch glossary index (generated by npm run generate-glossary-index)
        const response = await fetch('/glossary-index.json');
        const data: GlossaryIndex = await response.json();

        // Create Flexsearch index
        const searchIndex = new FlexSearch.Index({
          tokenize: 'forward',
          resolution: 9,
        });

        // Index all terms
        data.terms.forEach((term, idx) => {
          searchIndex.add(idx, `${term.term} ${term.definition}`);
        });

        setIndex(searchIndex);
        setGlossaryData(data.terms);
      } catch (error) {
        console.error('Failed to load glossary index:', error);
      }
    }

    loadGlossary();
  }, []);

  // Handle search input
  const handleSearch = (searchQuery: string) => {
    setQuery(searchQuery);

    if (!index || !searchQuery.trim()) {
      setResults([]);
      return;
    }

    // Search index
    const matchedIndices = index.search(searchQuery, { limit: 10 });
    const matchedTerms = matchedIndices.map((idx) => glossaryData[idx as number]);

    setResults(matchedTerms);
  };

  // Navigate to term in glossary
  const handleTermClick = (termId: string) => {
    window.location.href = `/docs/references/glossary#${termId}`;
  };

  return (
    <div className="glossary-search">
      <input
        type="text"
        placeholder="Search robotics terms... (e.g., SLAM, ROS 2, VLA)"
        value={query}
        onChange={(e) => handleSearch(e.target.value)}
        aria-label="Search glossary"
      />

      {query && (
        <div className="glossary-results">
          {results.length > 0 ? (
            results.map((result, index) => (
              <div
                key={index}
                className="glossary-result-item"
                onClick={() => handleTermClick(result.id)}
              >
                <div className="glossary-result-term">{result.term}</div>
                <div className="glossary-result-definition">
                  {result.definition.substring(0, 150)}
                  {result.definition.length > 150 ? '...' : ''}
                </div>
              </div>
            ))
          ) : (
            <div className="glossary-no-results">
              No terms found for "{query}". Try different keywords.
            </div>
          )}
        </div>
      )}
    </div>
  );
}
